### ISSUE TITLE
crashing 

### ISSUE THREAD

**Issue by senolfndk** [Goooler/LawnchairRelease#39]
Lawnchair bug report 25 Kas 2023 23:04:19 version: 13.0.0 (7da10fa) (13000000) commit: 7da10fa build.brand: samsung build.device: a21s build.display: SP1A.210812.016.A217FXXSADWI1 build.fingerprint: samsung/a21snstur/a21s:12/SP1A.210812.016/A217FXXSADWI1:user/release-keys build.hardware: exynos850 build.id: SP1A.210812.016 build.manufacturer: samsung build.model: SM-A217F build.security.level: 2023-09-01 build.product: a21snstur build.type: user version.codename: REL version.incremental: A217FXXSADWI1 version.release: 12 version.sdk_int: 31 display.density_dpi: 300 isRecentsEnabled: false error: Uncaught exception android.util.SuperNotCalledException: Activity {app.lawnchair/app.lawnchair.LawnchairLauncher} did not call through to super.onDestroy() 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5939) 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5995) 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6318) 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6212) 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71) 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:65) 	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6301) 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2448) 	at android.os.Handler.dispatchMessage(Handler.java:106) 	at android.os.Looper.loopOnce(Looper.java:226) 	at android.os.Looper.loop(Looper.java:313) 	at android.app.ActivityThread.main(ActivityThread.java:8669) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by Goooler** [comment]
Seems this had been fixed by 008a1f82ea0f5fab0fe8b7b8209e487a382f692a, I'll draft a new release.
