### ISSUE TITLE
[BUG] Death of custom At a Glance

### ISSUE THREAD

**Issue by bnhlll** [Goooler/LawnchairRelease#41]
Custom widget does not respond to system events + different in style

Screenshot:
![292263748-3c835102-0fde-4ddf-893a-dfcf1453d670](https://github.com/Goooler/LawnchairRelease/assets/57818513/3f63999c-4f45-4c70-ad68-6378bc1e780b)
![292263760-67573366-e52a-4a9c-9648-835bea909dba](https://github.com/Goooler/LawnchairRelease/assets/57818513/75c695d8-2e42-440d-a7a4-963a2f412bd6)

Steps to reproduce:
1.Connection to the charger
2.Playing media
3.Connecting Bluetooth devices

Expected behavior:
Matching the custom widget with the main one

Device information
Device: [Oneplus 9]
OS: [custom ROM Android version 13.0]
App version: [13 dev]

**Comment by Goooler** [comment]
Try LC 14 from the upstream repo, if it's not workable, file an issue to upstream.

**Comment by bnhlll** [comment]
I tried it, it didn't work
And reported
It’s just that Mr. Slaffy intercepted the problem and closed it in branch 14. I doubt that this is visible in 13

**Comment by MrSluffy** [comment]
> I tried it, it didn't work And reported It’s just that Mr. Slaffy intercepted the problem and closed it in branch 14. I doubt that this is visible in 13 [LawnchairLauncher#3902](https://github.com/LawnchairLauncher/lawnchair/issues/3902)

#3907

**Comment by Goooler** [comment]
Released at https://github.com/Goooler/LawnchairRelease/releases/tag/14.0.0-20231223.
