### ISSUE TITLE
Consider publishing on IzzyOnDroid

### ISSUE THREAD

**Issue by ThatOneCalculator** [Goooler/LawnchairRelease#43]
This would allow people to be able to get release updates from an app store, and would also fix the issue of having to manually allow restricted settings every update.

**Comment by Goooler** [comment]
The official release will be delivered via Google Play from upstream repo, check https://github.com/LawnchairLauncher/lawnchair/milestone/4.

**Comment by ThatOneCalculator** [comment]
Just the Play Store? There's an existing IzzyOnDroid build

![Screenshot_20231222-185014.png](https://github.com/Goooler/LawnchairRelease/assets/44733677/ddcd73d8-f60c-4d81-83a6-ba9a7bf17729)

**Comment by Goooler** [comment]
It might be auto published by LzzyOnDroid, upstream repo will be published to https://play.google.com/store/apps/details?id=ch.deletescape.lawnchair.plah

**Comment by Fxzzi** [comment]
I use Obtainium to grab updates and auto update these Lawnchair builds. You should check it out, it also supports f droid repos like Izzy.

https://github.com/ImranR98/Obtainium
![Screenshot_20240317-181722_Obtainium](https://github.com/Goooler/LawnchairRelease/assets/18248986/28975896-395b-46ea-b500-bae32676f782)

**Comment by ThatOneCalculator** [comment]
I use obtainium too, but that's not a permanent or widespread solution

**Comment by oniGino** [comment]
Currently following this fork on both pixel 8 and pixel tablet with zero issues so far.. 

Well once minor tablet problem

**Comment by Pyntux** [comment]
> Currently following this fork on both pixel 8 and pixel tablet with zero issues so far.. 
> 
> Well one minor tablet problem 

Do you have visual glitches on folder, after closing app opened from folder?

**Comment by oniGino** [comment]
> > Currently following this fork on both pixel 8 and pixel tablet with zero issues so far.. 
> > 
> > Well one minor tablet problem 
> 
> Do you have visual glitches on folder, after closing app opened from folder? 

No,  I very rarely get any artifacts and not from folders ever

**Comment by Pyntux** [comment]
> > > Currently following this fork on both pixel 8 and pixel tablet with zero issues so far.. 
> > > 
> > > Well one minor tablet problem 
> > 
> > Do you have visual glitches on folder, after closing app opened from folder? 
> 
> No,  I very rarely get any artifacts and not from folders ever

Strange... I always have glitches on folder, on Pixel 8...

**Comment by ThatOneCalculator** [comment]
Same, but that's off topic for this issue.
