### ISSUE TITLE
Smartspacer doesn't work

### ISSUE THREAD

**Issue by ThatOneCalculator** [Goooler/LawnchairRelease#44]
Smartspacer consistently doesn't show on the AAG or Feed section. This isn't a problem with the official debug build.

**Comment by Goooler** [comment]
Is this one workable?

[Lawnchair 14 Dev (1fd123f) market release.apk.zip](https://github.com/Goooler/LawnchairRelease/files/13758010/Lawnchair.14.Dev.1fd123f.market.release.apk.zip)

**Comment by ThatOneCalculator** [comment]
Yep, that one seems to work fine. Interestingly, after installing that version, Smartspacer re-appeared on the "main" Lawnchair version.

**Comment by Goooler** [comment]
After uninstalling this one, it will stil work?

**Comment by ThatOneCalculator** [comment]
Yep. Maybe the current release version wasn't getting Smartspacer to stay active?

**Comment by Goooler** [comment]
Wired, I should not modify anything related to Smartspacer.

**Comment by ThatOneCalculator** [comment]
Maybe it was just a one-off bug... I'll keep the regular version installed for now and let you know if it happens again.

**Comment by ThatOneCalculator** [comment]
I woke up, turned on my phone, and Smartspacer disappeared again

**Comment by Goooler** [comment]
I guess it will work after reboot. I've seen a similar phenomenon when using my weather widget, it works well on 12.1, need to file an issue to the upstream repo.

**Comment by Goooler** [comment]
> I guess it will work after reboot. I've seen a similar phenomenon when using my weather widget, it works well on 12.1,

Seems this has gone after I upgraded to A14, it might be a bug on A13 only.

**Comment by ThatOneCalculator** [comment]
I'm on A14 and it still happens for me almost every day.

**Comment by ThatOneCalculator** [comment]
This seems to have gone away with GrapheneOS's latest update

**Comment by devlocalhost** [comment]
![Screenshot_20240111-232827_Lawnchair](https://github.com/Goooler/LawnchairRelease/assets/56504654/43903d16-20e0-4397-a809-d6fc70a6afdf)
![Screenshot_20240111-232823_Smartspacer](https://github.com/Goooler/LawnchairRelease/assets/56504654/5fe06cfe-8273-42c1-bbc2-d8712e9354fa)
![Screenshot_20240111-232820_Smartspacer](https://github.com/Goooler/LawnchairRelease/assets/56504654/38f0d99e-93b5-43fe-a201-398b09eaf0e7)
Has anyone found a workaround? Id like having weather in the widget, like pixel launcher.

**Comment by ThatOneCalculator** [comment]
Not related to this issue.

**Comment by ThatOneCalculator** [comment]
Never mind, the issue is back.

**Comment by devlocalhost** [comment]
> Not related to this issue.

Why do you think so? Lol

**Comment by ThatOneCalculator** [comment]
You're talking about complications. I'm talking about the widget's integration with the Lawnchair AAG SDK. You have a different problem.

**Comment by ThatOneCalculator** [comment]
Not to jinx it, but as of the latest Lawnchair build, GrapheneOS update, and Smartspacer version, I don't think this occurs anymore.
