### ISSUE TITLE
POCO F5 Hyper OS latest Build Crash Launcher Application

### ISSUE THREAD

**Issue by Dhwanil20** [Goooler/LawnchairRelease#47]
**Before submitting an issue, please check if the same issue is presented in the upstream repository. 
If so, please file the issue to that repository instead.**

## Describe the bug
POCO F5 Hyper OS latest Build Crash Launcher Application. Randomly Crashing Application

**Comment by Goooler** [comment]
If this happens on upstream build artifacts? And need your crash stackrace.

**Comment by Goooler** [comment]
You can obtain it from the notification which shows after a crash.
