### ISSUE TITLE
[BUG] Weather not visible in At a Glance widget with Assistant off, visible on lockscreen

### ISSUE THREAD

**Issue by diegonogaretti** [Goooler/LawnchairRelease#54]
### Describe the bug

Weather is missing/not visible in At a Glance widget with Assistant off.
Feature is enabled in both Lawnchair's settings and At a Glance/Assistant's settings.
It's visible and correctly showing location and weather data on lockscreen, Google app is updated too.

1. Disable Assistant (I mean completely turn off in Assistant's settings)
2. Weather missing/not visible

Weather is visible and correctly showing location and weather data on lockscreen, should be on homescreen too.

- Device: [Google Pixel 8]
- OS: [stock ROM Android version 14.0]
- App version: [Goooler's latest release]

**Comment by Goooler** [comment]
Please check if the same issue is presented in the upstream repository. If so, please file the issue to that repository instead.

**Comment by diegonogaretti** [comment]
Hi
Did just a sec before this as I wasn't sure if it was better here or there, if so a can close this one.

**Comment by Goooler** [comment]
If it's the bug of the original LC, file to it, else leave it here.

**Comment by diegonogaretti** [comment]
I'm using your release as it's easy to install/update instead of compiling original LC.
Given yours is a fork I suppose the bug is of the original LC.

**Comment by Goooler** [comment]
Try the artifact from https://github.com/LawnchairLauncher/lawnchair/actions/runs/7770305439

**Comment by diegonogaretti** [comment]
Same problem

**Comment by Goooler** [comment]
Tracked by https://github.com/LawnchairLauncher/lawnchair/issues/4053.

**Comment by diegonogaretti** [comment]
Thanks.
