### ISSUE TITLE
[Request] armeabi-v7a version

### ISSUE THREAD

**Issue by MagicalDrizzle** [Goooler/LawnchairRelease#55]
So I know armeabi-v7a-only phones are rare to come by these days but I sadly am the owner of one...
This probably sound selfish but would you consider releasing an v7a version?
edit: I accidentally chose the bug form, my apologies

**Comment by Goooler** [comment]
Refixed, check https://github.com/Goooler/LawnchairRelease/releases/tag/14.0.0-20240326
