### ISSUE TITLE
[BUG] Folder icon artifacts

### ISSUE THREAD

**Issue by znbaboy** [Goooler/LawnchairRelease#56]
### Describe the bug

Device: Pixel 7 Pro
OS: LineageOS 20 (February 13th build)
Lawnchair version: 14.0.0-20240203

Artifacting around folders after closing out of an app opened from within the folder

![Screenshot_20240220-134835_Lawnchair~2](https://github.com/Goooler/LawnchairRelease/assets/52028136/07132f48-49cb-41c3-971c-20b8fcbefe48)

**Comment by Goooler** [comment]
Please check if the same issue is presented in the upstream repository. If so, please file the issue to that repository instead.
