### ISSUE TITLE
Navigation and back gesture unresponsive [BUG] 

### ISSUE THREAD

**Issue by usamaiqbal1177** [Goooler/LawnchairRelease#57]
### Describe the bug

Sometimes the navigation bar gestures and back gestures doesn't work or the current app becomes unresponsive. In that case, I have to press swipe up on nav bar a couple of times and then it goes to home screen...

This is quote frequent and happens very randomly.

Pixel 8 Pro stock android 14 February

**Comment by Goooler** [comment]
Duplicate of https://github.com/LawnchairLauncher/lawnchair/issues/4050
