### ISSUE TITLE
[BUG]  feed

### ISSUE THREAD

**Issue by Bertklq1** [Goooler/LawnchairRelease#59]
### Describe the bug

Selecting google as feed provider does nothing., there's no google feee section in home screen

**Comment by Goooler** [comment]
Please check if the same issue is presented in the upstream repository. If so, please file the issue to that repository instead.

**Comment by Bertklq1** [comment]
The latest development preview of lawnchair 14 doesn't have this issue.

**Comment by Bertklq1** [comment]
The issue is still there. Why did you close it @Goooler

**Comment by Goooler** [comment]
Define "The latest development preview of lawnchair 14".
