### ISSUE TITLE
[BUG] Visual artifacts around folders

### ISSUE THREAD

**Issue by Pyntux** [Goooler/LawnchairRelease#60]
### Describe the bug

There are visual artifacts around folder when I close app opened from that folder. That only happens when in folder is more than 3 apps (icons)... There is similar bug:

https://github.com/LawnchairLauncher/lawnchair/issues/3983

Google Pixel 8, android 14

**Comment by Goooler** [comment]
Please check if the same issue is presented in the upstream repository. If so, please file the issue to that repository instead.
