### ISSUE TITLE
Dark2normal mode[BUG] 

### ISSUE THREAD

**Issue by Zero00000000000000000000** [Goooler/LawnchairRelease#62]
### Describe the bug

While Changing the mode dark to norml the transparent app icon goes to black....its hard to see these apps....make white for better visiblity..
![Screenshot_20240323-151404_Lawnchair](https://github.com/Goooler/LawnchairRelease/assets/94057602/3b9d62e6-0592-4bc6-b6a6-4f8096381602)

**Comment by Goooler** [comment]
Please check if the same issue is presented in the upstream repository. If so, please file the issue to that repository instead.
