### ISSUE TITLE
[BUG] one-tapping the navbar pill makes the current app unresponsive

### ISSUE THREAD

**Issue by Lelonio** [Goooler/LawnchairRelease#65]
### Checklist

- [X] No one has submitted a similar or identical bug report before.
- [X] Please check if the same issue is presented in [the upstream nightly artifact](https://github.com/LawnchairLauncher/lawnchair/releases/tag/nightly). If so, please file the issue to that repository instead.

### Describe the bug

As the title says. Using latest Goooler release + latest quickswitch on LineageOS 21.

**Comment by Goooler** [comment]
Have you checked https://github.com/LawnchairLauncher/lawnchair/releases/tag/nightly?

**Comment by Lelonio** [comment]
> Have you checked https://github.com/LawnchairLauncher/lawnchair/releases/tag/nightly?
What i have to check specificly?
