### ISSUE TITLE
Question: feature missing 

### ISSUE THREAD

**Issue by Bertklq1** [Goooler/LawnchairRelease#66]
### Checklist

- [X] No one has submitted a similar or identical bug report before.
- [X] Please check if the same issue is presented in [the upstream nightly artifact](https://github.com/LawnchairLauncher/lawnchair/releases/tag/nightly). If so, please file the issue to that repository instead.

### Describe the bug

Latest release doesn't have "show when full name is typed" feature under hidden apps option that was available in previous release

**Comment by Goooler** [comment]
That's the upstream's issue.
