### ISSUE TITLE
Transparency in Appdrawer [BUG] 

### ISSUE THREAD

**Issue by Zero00000000000000000000** [Goooler/LawnchairRelease#67]
### Checklist

- [X] No one has submitted a similar or identical bug report before.
- [X] Please check if the same issue is presented in [the upstream nightly artifact](https://github.com/LawnchairLauncher/lawnchair/releases/tag/nightly). If so, please file the issue to that repository instead.

### Describe the bug

App drawer transparency is constant...the value changed bt exist a constant transparency or blur in app drawer
![Uploading Screenshot_20240501-174703_Lawnchair.png…]()

**Comment by Goooler** [comment]
Please check if the same issue is presented in [the upstream nightly artifact](https://github.com/LawnchairLauncher/lawnchair/releases/tag/nightly). If so, please file the issue to that repository instead.
